version : "3.7"
services :
  proyectos-monolito : 
    container_name : proyectos-monolito
    image : proyectos-monolito:v1
    build :
      context : .
    ports : 
      - "4037:4037"
    networks : 
      - proyectos-app
networks : 
  proyectos-app :  